CREATE TABLE user (
 id INT(11) NOT NULL AUTO_INCREMENT,
 name VARCHAR(50) NOT NULL,
 password VARCHAR(50) NOT NULL,
 PRIMARY KEY (id)
);

CREATE TABLE post (
 id INT(11) NOT NULL AUTO_INCREMENT,
 title VARCHAR(100) NOT NULL,
 content LONGTEXT NOT NULL,
 creationtime DATETIME NOT NULL,
 user_id INT(11) NOT NULL,
 PRIMARY KEY (id)
);

CREATE TABLE comment (
id INT(11) NOT NULL AUTO_INCREMENT,
content LONGTEXT NOT NULL,
creationtime DATETIME NOT NULL,
post_id INT(11) NOT NULL,
user_id INT(11) NOT NULL,
PRIMARY KEY (id)
);